project:
  name: "The Calculator"
  metadata:
    Vendor: "Endocode"
    OcFossLiaison: "Mirko Boehm"
    OcComplianceContact: "foss@endocode.com"
  analysis:
    - analyzer: spdx-identifier-analyzer
      name: "Simple SPDX Analyzer"
      trustlevel: 300
      config:
        workdir: "/home/qmstr/buildroot/"
    - analyzer: test-analyzer
      name: "Simple CI Test Analyzer"
      config:
        workdir: "/home/qmstr/buildroot/"
        tests: "TestPackageNode;TestCalcBuildGraph"
  reporting:
    - reporter: test-reporter
      name: "Test Reporter"
      config:
        siteprovider: "Endocode"
